### ISSUE TITLE
Make Settings Button More Responsive

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#143]
This should be an easy fix because it's just a matter of positioning and styling. Right now the settings button on the Reward page awkwardly covers the side panel when it is open.

Let's make this more responsive so that the settings button follows the side panel. Use your intuition with this in terms of placement:)

**Comment by Charlitoes** [comment]
maybe instead of moving the setting button along with the setting bar we could put a X button and make the setting button disappear if the bar is out? The reason why I mention this is because the settings button is pretty big compared to the bar so I think it would look kinda weird if we were to move the settings button along side with the setting bar.

If we over all agree with this I could implement this fix

**Comment by milgor931** [comment]
That sounds like a great solution! I'm cool with it and it makes sense:)

**Comment by milgor931** [comment]
Fixed by  the Sidebar bug fixes PR
